export const SET_GEOLOCATION = 'SET_GEOLOCATION';
export const SET_GEOLOCATION_WITH_WEATHER = 'SET_GEOLOCATION_WITH_WEATHER';
export const IS_VALID_GEO_LOCATION = 'IS_VALID_GEO_LOCATION';

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const SET_CURRENT_CITY_WITH_WEATHER = 'SET_CURRENT_CITY_WITH_WEATHER';
export const SET_CITIES = 'SET_CITIES';

export const SET_WEATHER = 'SET_WEATHER';
export const SET_AIR_QUALITY = 'SET_AIR_QUALITY';
export const SET_USER_NAME = 'SET_USER_NAME';

export const FETCH_WEATHER_BY_GEO = 'FETCH_WEATHER_BY_GEO';
export const FETCH_WEATHER_BY_CITY = 'FETCH_WEATHER_BY_CITY';
export const FETCH_AIR_QUALITY_BY_CITY = 'FETCH_AIR_QUALITY_BY_CITY';

export const NEED_LOGIN = 'NEED_LOGIN';
