export const SET_GEOLOCATION = 'SET_GEOLOCATION';
export const DESTROY_GEOLOCATION = 'DESTROY_GEOLOCATION';
export const SET_GEOLOCATION_WITH_WEATHER = 'SET_GEOLOCATION_WITH_WEATHER';
export const IS_VALID_GEO_LOCATION = 'IS_VALID_GEO_LOCATION';

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export const SET_CURRENT_CITY_WITH_WEATHER = 'SET_CURRENT_CITY_WITH_WEATHER';
export const DESTROY_CURRENT_CITY = 'DESTROY_CURRENT_CITY';
export const SET_CITIES = 'SET_CITIES';

export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_AIR_QUALITY = 'SET_AIR_QUALITY';
export const SET_USER_NAME = 'SET_USER_NAME';

export const START_CLOCK = 'START_CLOCK';
export const UPDATE_TIME = 'SET_NOW';
export const GET_TIME = 'GET_TIME';
export const GET_DAY_NIGHT = 'GET_DAY_NIGHT';
export const SET_WEATHER_PHOTO = 'SET_WEATHER_PHOTO';
export const GET_WEATHER_ICON = 'GET_WEATHER_ICON';

export const GET_TEMPERATURE = 'GET_TEMPERATURE';

export const FETCH_WEATHER_BY_GEO = 'FETCH_WEATHER_BY_GEO';
export const FETCH_WEATHER_BY_CITY = 'FETCH_WEATHER_BY_CITY';
export const FETCH_AIR_QUALITY_BY_CITY = 'FETCH_AIR_QUALITY_BY_CITY';

export const NEED_LOGIN = 'NEED_LOGIN';
export const RESET_CURRENT_CITY = 'RESET_CURRENT_CITY';
